### PR TITLE
3.0

### PR DESCRIPTION
**Pull request by kleffa**
try to add Whatsapp, but not sure whats wrong, please check if something wrong

### CODE REVIEW

**Comment by luc-github** [comment]
I do not know what it does not work but  you should not need  the callbot headers . I also saw some bad copy and paste refering homeassistant instead of whatspp...

**Comment by kleffa** [comment]
I corrected but still
Arduino:1.8.19 (Windows 10), Tarjeta:"AI Thinker ESP32-CAM, 240MHz (WiFi/BT), QIO, Huge APP (3MB No OTA/1MB SPIFFS), 80MHz, None, Disabled"
C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp: In function 'bool processingFileFunction(const char*, const char*, const char*)':

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:402:30: error: cannot call constructor 'UpdateService::UpdateService' directly [-fpermissive]

 UpdateService::UpdateService() {};

                              ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:402:30: note: for a function-style cast, remove the redundant '::UpdateService'

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:402:31: error: expected ';' before '{' token

 UpdateService::UpdateService() {};

                               ^~

                               ;

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:403:31: error: no matching function for call to 'UpdateService::~UpdateService()'

 UpdateService::~UpdateService() {};

                               ^

In file included from C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:29:

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.h:29:5: note: candidate: 'UpdateService::~UpdateService()'

     ~UpdateService();

     ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.h:29:5: note:   candidate expects 1 argument, 0 provided

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:405:26: error: qualified-id in declaration before '(' token

 bool UpdateService::flash(const char* filename, int type) {

                          ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:462:26: error: qualified-id in declaration before '(' token

 bool UpdateService::begin() {

                          ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:497:24: error: qualified-id in declaration before '(' token

 void UpdateService::end() {}

                        ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:499:27: error: qualified-id in declaration before '(' token

 void UpdateService::handle() {}

                           ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:499:31: error: expected '}' at end of input

 void UpdateService::handle() {}

                               ^

C:\Users\kleff\Desktop\ESP3D-3.0\esp3d\src\modules\update\update_service.cpp:179:48: note: to match this '{'

                             const char* value) {

                                                ^

Se encontraron varias bibliotecas para "WiFi.h"

Usado: C:\Users\kleff\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.16\libraries\WiFi

 No usado: C:\Program Files (x86)\Arduino\libraries\WiFi

exit status 1

Error compilando para la tarjeta AI Thinker ESP32-CAM.

**Comment by luc-github** [comment]
do you have same issue without your PR?
What esp32 core version are you using?

**Comment by kleffa** [comment]
I compiled it well like 3 days ago, same files, working well, using a esp32cam AI thinker, since most troubles cames from src\modules\update\update_service.cppo , there is something I didnt see there?

**Comment by luc-github** [comment]
I see line  313 {{ I think only one { is necessary no ? 
I am on phone I cannot see more

**Comment by kleffa** [comment]
I did it, but now I'm looking for esp610 where is defined? Because I can't
test it because invalid parameter

**Comment by luc-github** [comment]
https://github.com/kleffa/ESP3D/blob/3.0/esp3d/src/core/commands/ESP610.cpp

**Pull request closed without merging**
