### PR TITLE
3.0 : MQTT Client

### PR DESCRIPTION
**Pull request by AFUman**
Hello, we are already planning to install an MQTT client. Then I could integrate the messages into my smart home and know if something is not going with the print.

### CODE REVIEW

**Comment by luc-github** [comment]
May I know what you are trying to do with PR?

Pushing code from 3.0 to 2.1 is not possible

**Comment by AFUman** [comment]
I would like to connect iobroker to the ESP3D via MQTT. So that I can get the information in the whole house whether a print is running or if it is finished. You could then e.g. output this via Alexa or receive information via Telegram.

**Comment by luc-github** [comment]
so you will do the code?

**Comment by AFUman** [comment]
No, unfortunately I can't, I'm not a coder. That was just a question of whether it could be built into a newer version.

**Comment by luc-github** [comment]
then I already answered here https://github.com/luc-github/ESP3D/issues/403

**Pull request closed without merging**
