### PR TITLE
A python webserver to help working on the template files

### PR DESCRIPTION
**Pull request by j0hnlittle**
Hello,

I wrote this very simple server to help me understand how your .tpl files work and look like (very nice!).

So launching server.py in windows / linux will create a webserver on port 8080 which serves files stored in ESP8266/data (the base_path can be changed if needed).

For now, the server only understands $INCLUDE[filename.inc]$ type statements (with filename.inc in the same folder as the .tpl file).

Maybe worth looking at including (some of) the $$ key / values in a JSON file to display as well. This may help with translation efforts (maybe).

Anyway, love what you've done and am hoping to be able to use this in my own projects!

Cheers,
John

### CODE REVIEW

**Comment by j0hnlittle** [comment]
I have now added some rudimentary json file processing. This is entirely optional but will help filling some blanks.

**Comment by luc-github** [comment]
Hi thank you and it is indeed a good idea to be able to simulate web UI.
I would suggest to locate server.py in directory named "tools" as root is mostly used for readme and travis and it is already messy. It is for python 2.7+ or 3.1+ ?

Sorry I am not familiar with json but to be used as data exchange, what is the purpose of json tags in data directory ? what action use it ?

**Comment by j0hnlittle** [comment]
> I would suggest to locate server.py in directory named "tools" as root is mostly used for readme and travis and it is already messy.

No worries! It shouldn't be too difficult to move the file to tools, I just need to read the git docs as to how to do it cleanly.

> It is for python 2.7+ or 3.1+ ?

python 2.7 for now. I haven't checked compatibility with 3+

> Sorry I am not familiar with json but to be used as data exchange, what is the purpose of json tags in data directory ? what action use it ?

From what I've seen, json is (will be?) used instead of XML for storing config variables in a single file in SPIFFS.

This thread for example has some code that I still need to look into: http://www.esp8266.com/viewtopic.php?f=32&t=6436

In my case, I want to have some sensible settings that I could just upload to SPIFFS as a single file. I was thinking by extension that you may be able to leverage the same method to store i18n strings for some of the $keywords$ you have defined. For security, it should be possible to prevent the ESP8266 from serving the .json files.

Anyway, just a thought. For now, the tags.json file will provide some added text when simulating / testing your template interfaces.

Cheers!

**Comment by luc-github** [comment]
Yes json file can replace xml, I was not sure what purpose you wanted to use.

you need to be careful putting settings in json file on SPIFFS, currently all files are accessible by web interface, even not authenticate, so you need to modify FW to limit access to this file.

about $keyword$ in SPIFFS need to see the impact on ESP with 1M flash /128K SPIFFS but could be a  good idea if no performance/memory lost, need to evaluate memory /cpu usage to parse the file for each $keyword$

**Comment by j0hnlittle** [comment]
> I would suggest to locate server.py in directory named "tools" as root is mostly used for readme and travis and it is already messy.

All done! Painless procedure through the github website. If you have a sec, let me know if the server works for you. I'm hoping to use it in conjunction with Firefox / Firebug, maybe add some [Pure.css](http://purecss.io/) if space allows.

> you need to be careful putting settings in json file on SPIFFS, as you mentionned currently all files are accessible by web interface, even not authenticate, so you need to modify FW to limit access to this file.

Thank you, this is the next item on my list! I am looking at your sketch and [FSBrowser.ino](https://github.com/esp8266/Arduino/tree/master/libraries/ESP8266WebServer/examples/FSBrowser) for reference. Restricting access to files should be possible, I just need to decide how I'm going to do it.

In any case, I will document my code / efforts on github.

Cheers,
John

**Comment by luc-github** [comment]
I would suggest here : https://github.com/luc-github/ESP8266/blob/master/esp8266/webinterface.cpp#L2735
and to check if path do not match your tag file, or if file name start by "restricted" reject the request, so this can apply to several files with only one check

**Comment by luc-github** [comment]
I won't be able to really play with your code before this week end, sorry - but will feed back next week for sure

**Comment by j0hnlittle** [comment]
Thanks for the pointers!

> I won't be able to really play with your code before this week end, sorry - but will feed back next week for sure

No worries, this gives me a bit of time to do my own in-depth testing and add things if needed.

Cheers,
John

**Comment by luc-github** [comment]
will start next week (18th of Jan) to test your code - thanks

**Comment by luc-github** [comment]
I played with the tool
Very nice indeed and very useful I think
I found one issue :
```$INCLUDE[footer.inc]$ ``` is not processed if at the end of the file but ok if at the beginning - 
I did not dig in the code a lot, but I have 3 suggestions:
1 - if no page served, display content of data directory, list all files and allow them to be selected like  in normal web server.
2 - add a sentence when server is starting saying : 
```please connect to server http://127.0.0.1:8080/<yourfile.tpl>```
this will make usage very obvious
3 - allows as fw to have include in include so you need recursive functions (this one is only for advanced users I think, most of people won't use this feature and keep tpl/inc simples) this is just for consistency and it can be a future feature

Excellent start, if later can navigate using menu bar will be great but currently if suggestion 1 is done - it may no need

**Comment by luc-github** [comment]
Do you want I merge now or you want to implement  fix / suggestions first ?

**Comment by luc-github** [comment]
seems I used wrong version - latest code do not have the header.inc not processed - my mistake
I merge it
Thank you

**Comment by luc-github** [comment]
@all-contributors please add @j0hnlittle for code improvement

**Pull request merged**
