### PR TITLE
(v2) Add Home Assistant notification support

### PR DESCRIPTION
**Pull request by dbuezas**
/* *** Home Assistant notification ***
 * Home Assistant tokens are too long to pass via serial.
 * Create a long-lived access token here: http://homeassistant.local:8123/profile
 * And replace "YOUR-TOKEN" below.
 * Usage: In a Marlin custom menu or at the end of your gcode add:
     M118 [ESP610]type=POST TS=#homeassistant.local:8123
     M118 [ESP600]/api/services/switch/toggle#{"entity_id": "switch.3d_printer_switch"}
*/

#define HOME_ASSISTANT_TOKEN "YOUR TOKEN"

Tested in an esp8266.

### CODE REVIEW

**Comment by dbuezas** [comment]
In Marlin's `Configuration_adv.h`
```cpp
  #define MAIN_MENU_ITEM_1_DESC "Turn Off"
  #define MAIN_MENU_ITEM_1_GCODE "M118 [ESP610]type=POST TS=#homeassistant.local:8123\nM118 [ESP600] /api/services/switch/toggle#{\"entity_id\": \"switch.3d_printer_tuya_plug_5_switch\"}"
  #define MAIN_MENU_ITEM_1_CONFIRM          // Show a confirmation dialog before this action
  
  #define MAIN_MENU_ITEM_2_DESC "Toggle Room Light"
  #define MAIN_MENU_ITEM_2_GCODE "M118 [ESP610]type=POST TS=#homeassistant.local:8123\nM118 [ESP600] /api/services/light/toggle#{\"entity_id\": \"light.wintergarten_spots\"}"
```

The printer is connected to a smart switch.

https://github.com/luc-github/ESP3D/assets/777196/84cf0cca-8f53-495c-8cae-a937c05a65a4

**Comment by luc-github** [comment]
What is the length of home assistant token usually ?
 why not put it in T1 ?

adding `M118 [ESP610]type=POST TS=#homeassistant.local:8123` in gcode is little bit overkill IMHO

**Comment by dbuezas** [comment]
> What is the length of home assistant token usually ?
> why not put it in T1 ?

That would have been ideal, but it is 183 characters long (not sure if it is always the same length).
If there is another way, I'll happily try it out. I don't like it needs to be baked in the fw at all.

> adding M118 [ESP610]type=POST TS=#homeassistant.local:8123 in gcode is little bit overkill IMHO

True, particularly if the token needs to be baked in the firmware...
You mean because it only needs to be done once, or because I am misusing the email parser?

**Comment by luc-github** [comment]
>You mean because it only needs to be done once, or because I am misusing the email parser?

Yes only need to be done once 

>That would have been ideal, but it is 183 characters long (not sure if it is always the same length).
If there is another way, I'll happily try it out. I don't like it needs to be baked in the fw at all.

Well 2.1.X is not supposed to merge new features only bugfix
3.0 is the one that get new features and as not yet released I think it is ok to extend the T1 to 255, from another point of view 3.0 already support IFTTT using webhook so it may be also possible to use it out of the box doing some config on IFTTT => TBC

Also this process is definitly for HOMEASSISTANT so it should be called HomeAssistant not POST - or I miss something ?

**Comment by dbuezas** [comment]
Oh, it's just a post request actually, I shouldn't have called the token like that.
I couldn't make v3 work on an esp8266, and I tried IFTTT but it didn't work well for me. One of the points of home assistant is to not depend on a cloud, so for this kind of folks like me, IFTTT is more of an annoyance.

It would be terrific if one could do generic get and post requests via gcode, then any rest api would be accessible.

I understand it if you aren't taking PRs for v2, I mostly did this for myself. Maybe someone finds this in the PRs and can use it too.

Finally, an annoyance of the slicer I'm using (OrcaSlicer) is that the gcode macros for layer change don't like curly brackets, so to send the print progress via post request I had to pass the gcode through a post-processing script.

**Comment by luc-github** [comment]
>Oh, it's just a post request actually, I shouldn't have called the token like that.

I think it is reasonable to call it for HOMEASSISTANT  because it use specific process : Autorization Header  + specific URL 

Ok good to know it is not easy to use IFTTT - in that case it is a pro in integration in ESP3D 

>One of the points of home assistant is to not depend on a cloud, so for this kind of folks like me, IFTTT is more of an annoyance.

Another pro to integrate in ESP3D then

>It would be terrific if one could do generic get and post requests via gcode, then any rest api would be accessible.

there are so many possible parameters involved that it not easy , possible but not easy.

>I couldn't make v3 work on an esp8266

Weird it is using same API, I will check if I can add it to ESP3D 3.0  when I have time then, same for ESP3D-TFT 1.0 as they should follow same level of features

**Comment by dbuezas** [comment]
On the esp8266 I got endless watchdog resets, fully erasing flash didn't help either.
Looking forward to a stable release of v3, and thanks for your work, I really enjoy this project

**Comment by luc-github** [comment]
>On the esp8266 I got endless watchdog resets, fully erasing flash didn't help either.
Looking forward to a stable release of v3, and thanks for your work, I really enjoy this project

Hmm 3.0 works well on esp8266, it is actually very stable , it is set as alpha because of missing features that is all
I am currently working on a rewrite part to sync some API with ESP3D-TFT but current branch is quite stable 
What ESP8266 are you using ? ESP01 with 1MB flash or ESP12/X with 4MB flash ?

**Comment by dbuezas** [comment]
It's an [esp-07s from bigtreetech](https://biqu.equipment/collections/expansion-board/products/btt-esp-07s) with 4mb of flash.

I assumed it just wasn't stable for esp8266 yet. I'll have to try it once more then

**Comment by dbuezas** [comment]
Alright, I now tried your latest commit in the `Refactoring-internal-clients` and it worked first try. I'll move to that one and make a pr to v3 then.

**Comment by dbuezas** [comment]
Finished for v3 instead https://github.com/luc-github/ESP3D/pull/971

**Pull request closed without merging**
