### PR TITLE
update wiki and readme

### PR DESCRIPTION
**Pull request by atsju**
For wiki I only changed around line 77 (compare by ignoring whitespaces) because the title "Installation" was very unclear to me.

### CODE REVIEW

**Comment by luc-github** [comment]
trailling space in markdown have a purpose -  they do line break as a return do not do it
original ReadMe
image

after your PR :
image

I agree some may be overkill - but you removed too many - I did not checked all 

please revert the trailling commit and the .vscode part

**Comment by atsju** [comment]
Thanks for feedback. Too much confidence into VScode trailing whilespace cleaner. I'm currenty trying to use your code for the first time. I will continue this PR until I finished the process

**Comment by luc-github** [comment]
Markdown can be a pain - I remember there is a Markdown renderer as extension in VS code - it may help and save your time

**Comment by atsju** [comment]
> Markdown can be a pain - I remember there is a Markdown renderer as extension in VS code - it may help and save your time

Pretty cool. Didn't know it. Unfortunatelly It displays well in VScode and bad in GH. I also found a [linter](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint). Maybe the way you used spaces is a bit controversial and linter will help using the correct coding style. I will check...

**Comment by atsju** [comment]
You can have a look if it's Ok for you.
I would like to make the v3 and/or on platformIO documentation but well... Let's see later

**Comment by luc-github** [comment]
looking at https://github.com/atsju/ESP3D/blob/JST/updateWiki/wiki/Install-Instructions.md
you do not like markup trailling space ^_^
2.1 2.2 etc, 3.1 3.2 etc, 4.1 4.2 etc 5.1 5.2 etc... are all in one line instead of being displayed properly

**Comment by atsju** [comment]
I will fix it.

**Comment by atsju** [comment]
I did never use markdown heavily before. 
I'm currently linting all MD files here https://github.com/atsju/ESP3D/tree/JST/linting
respecting the rules from this VScode extension https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
This will be pushed to a different PR. After linting I may rework the wiki a bit if you agree

**Comment by luc-github** [comment]
Ok step by step is good
Thank you for your help

**Pull request merged**
