### PR TITLE
Support for image capture on ESP32-CAM modules

### PR DESCRIPTION
**Pull request by jackmax**
I added code to allow ESP32-CAM modules to capture images and send them over the network. One step closer to having the same functionality as Octoprint, but for a fraction of the price ;)

Code is adapted from [Espressif's example web server](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer). Fits in 1227566 bytes of Flash, even though I use a separate web server for streaming images. I also added a new endpoint to the default web server to get and set camera parameters.

The camera.html file is also adapted from the example, it could use some cleanup, optimization and styling to fit with the rest of interface. I'm not good with web development though, so maybe I'll leave it to someone else. 

To allow `/camera.html` to be displayed in the iframe, I modified `index.html` and changed
```t.indexOf("rtp://")&&(e="http://"+e)```
to
```t.indexOf("rtp://")&&(!(t.startsWith("/")))&&(e="http://"+e)```

Below is a screenshot of the new firmware in action:
Screenshot 2022-07-16 at 23-35-00 EspPrinter

### CODE REVIEW

**Comment by sschimansky** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre E-Mail.

Ich bin bis zum 2. August 2022 nicht im Büro und habe nur beschränkten Zugriff auf meine E-Mails. 

Bitte wenden Sie sich in dringenden Fällen an:

Herrn Matthias Christoph
Tel.: 05321-7591-73 60
***@***.***


Viele Grüße aus Goslar,
Sebastian Schimansky
Leiter IT-Abteilung, Entwicklung

Tel.: +49 (0) 5321-7591-62
Fax: +49 (0) 5321-7591-69

TMA TourismusMarketing Agentur GmbH | Spitalstraße 1 | D-38640 Goslar | www.tourismus-agentur.de |Sitz der Gesellschaft: Goslar | Geschäftsführer: Ralf Hummel | Ust-IdNr. DE 233056626 | HRB 111371 - AG Braunschweig



I added code to allow ESP32-CAM modules to capture images and send them over the network. One step closer to having the same functionality as Octoprint, but for a fraction of the price ;)

Code is adapted from [Espressif&#39;s example web server](https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/Camera/CameraWebServer). Fits in 1227566 bytes of Flash, even though I use a separate web server for streaming images. I also added a new endpoint to the default web server to get and set camera parameters.

The camera.html file is also adapted from the example, it could use some cleanup, optimization and styling to fit with the rest of interface. I&#39;m not good with web development though, so maybe I&#39;ll leave it to someone else. 

To allow `/camera.html` to be displayed in the iframe, I modified `index.html` and changed
```t.indexOf(&quot;rtp://&quot;)&amp;&amp;(e=&quot;http://&quot;+e)```
to
```t.indexOf(&quot;rtp://&quot;)&amp;&amp;(!(t.startsWith(&quot;/&quot;)))&amp;&amp;(e=&quot;http://&quot;+e)```

Below is a screenshot of the new firmware in action:
Screenshot 2022-07-16 at 23-35-00 EspPrinter


You can view, comment on, or merge this pull request online at:

  https://github.com/luc-github/ESP3D/pull/786

-- Commit Summary --

  * Support for image capture on ESP32-CAM modules.

-- File Changes --

    M esp3d/config.h (7)
    A esp3d/data/camera.html (718)
    A esp3d/esp32camera.h (31)
    A esp3d/esp32camera_stream.cpp (240)
    A esp3d/esp32camera_webcfg.cpp (229)
    M esp3d/esp3d.cpp (9)
    M esp3d/espcom.cpp (15)
    M esp3d/espcom.h (1)
    M esp3d/syncwebserver.cpp (57)
    M esp3d/syncwebserver.h (1)
    M esp3d/webinterface.cpp (1)

-- Patch Links --

https://github.com/luc-github/ESP3D/pull/786.patch
https://github.com/luc-github/ESP3D/pull/786.diff

-- 
Reply to this email directly or view it on GitHub:
https://github.com/luc-github/ESP3D/pull/786

**Comment by luc-github** [comment]
the feature is already in ESP3D V3 and webui V3 did you tested it ? 

camera

https://github.com/luc-github/ESP3D/tree/3.0
https://github.com/luc-github/ESP3D-WEBUI/tree/3.0

you can also save on ESP32 SD card now https://github.com/luc-github/ESP3D/issues/778

**Comment by jackmax** [comment]
I tested it now. 
* Looks nicer, but lacks configuration features, for example to set the resolution or use LED flash. I noticed camera settings can be changed by making GCode macros, or by embedding `esp32cam.html` like this:
screenshot
* `esp32cam.html` can change camera settings, but no longer works to preview the camera image (takes one picture, then the page has to be refreshed). It would be nice if it did, so you can have a bigger preview of the image.
* Setting camera resolution works incorrectly, e.g. `UXGA(1600x1200)` actually sets resolution to 1024x768, `SXGA(1280x1024)` to 800x600, etc.
* Code doesn't compile when `CAMERA_DEVICE` is set to `CAMERA_MODEL_CUSTOM`. This is because 
  `CAMERA_MODEL_TTGO_T_JOURNAL`
  `CAMERA_MODEL_M5STACK_PSRAM_2`
  `CAMERA_MODEL_M5STACK_ESP32CAM`
  `CAMERA_MODEL_M5STACK_UNITCAM`
  are not defined, so in expressions like `#if CAMERA_DEVICE == CAMERA_MODEL_TTGO_T_JOURNAL` the `CAMERA_MODEL_TTGO_T_JOURNAL` defaults to 0, which is the same number as `CAMERA_MODEL_CUSTOM`. As a result, the compiler attempts to redefine `#define` values.
* A compile-time sanity check to ensure `ESP3D_RESET_PIN` doesn't collide with camera pins would be nice. By default pin 0 is used and with camera enabled puts MCU in a reboot loop (very fun if you use OTA).
* Perhaps you could update README.md in https://github.com/luc-github/ESP3D/tree/3.0 with description of new features? I see there's an Excel spreadsheet describing them, but you can't even preview it on Github.

I guess it's good enough so I'll close this PR.

**Comment by luc-github** [comment]
About configurations / compilations I did this to avoid such issues :
https://github.com/luc-github/ESP3D-Configurator
which is live here: https://luc-github.github.io/

The CAMERA_MODEL_TTGO_T_JOURNAL should not be in pins list , the define is even not it list  so it is set 0 - I forget to remove it - thank you for pointing this out,  I have removed it 

The led flash is disabled on  ESP32Cam because it conflict with SD Card per my tests, but you can override the setting by controling pin directly with a macro 

The camera settings can be added by macro because they do not need to be in main page, because you do not change them all the time, this is not an outside camera, also if you want bigger output of camera you can put the camera output in full page instead of panel, so you will have dedicated page for camera
  
about features there is a file already : https://github.com/luc-github/ESP3D/blob/3.0/Features.md

**Pull request closed without merging**
