### PR TITLE
added whatsaap where i found 3.0

### PR DESCRIPTION
**Pull request by kleffa**
WhatsApp added for notifications
[ESP610] works in console. UI says not valid.
[ESP600] didn´t work, but its compile and almost near to that

notification, may have trouble with phone starting with a "+" but not sure.
also WAIT4response is not active in there

### CODE REVIEW

**Comment by luc-github** [comment]
sorry, so your PR is not working in fact?

**Comment by kleffa** [comment]
It compiles, but at try  just give a send notification failed, maybe
changing the method on the httpclient... But everythingelse is setup

**Comment by luc-github** [comment]
ok so it is not working yet - let me know when you solve the issue

**Comment by kleffa** [comment]
I have no idea what is wrong, this should just make a call for https client, but nothing, just return "Send notification failed", any idea of what happening, is welcome 


// WhatsApp, token1 phone, token2 apikey
bool NotificationsService::sendWhatsAppMSG(const char* title,
                                                const char* message) {
  const String hostS = "https://api.callmebot.com/";
  const String host  = "http://api.callmebot.com/";
  String URL = "whatsapp.php?phone=" ;
  URL += _token1    ;
  URL += "&apikey=" ;
  URL += _token2    ;
  URL += "&text="   ;
  URL += urlEncode(message) ;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
  WiFiClientSecure Notificationclient;
#pragma GCC diagnostic pop
  Notificationclient.setInsecure();
#if defined(ARDUINO_ARCH_ESP8266)
  BearSSLSetup(Notificationclient);
#endif  // ARDUINO_ARCH_ESP8266

//  Callmebot.whatsappMessage(_token1, _token2, message); //basically the same as here

  Notificationclient.setCACert(cert_ISRG_Root_X1); //from callmebot library
  HTTPClient https;
  https.begin(Notificationclient, hostS+URL);
  int httpCode = https.GET();

Serial.println(URL) ; 
  const char* Message_queued = "<b>Message queued.</b> You will receive it in a few seconds.";
  bool res =Wait4Answer(Notificationclient, "Message queued" , Message_queued, WHATSAPPTIMEOUT);
  
  https.end();
  Notificationclient.stop();
 
  return res;
}

**Comment by luc-github** [comment]
you do not need the callbot certificat normally becauseI set connection insecure it will use the default one
no need the http url neither only https one will be used
you do not do the `Notificationclient.connect(...` so I doubt anything work

**Comment by luc-github** [comment]
I close PR - reopen when ready

**Pull request closed without merging**
