### PR TITLE
Add esp01s environment to be able to build and upload from command line

### PR DESCRIPTION
**Pull request by padcom**

### CODE REVIEW

**Review by luc-github — COMMENTED** [review]
why comment the frequency 160Mhz ? at 80Mhz the response are slow

**Comment by padcom** [comment]
I did that because the ESP01S that I have was having issues connecting to the WiFi. Might be because it has no shield like the 07 or 12 modules have.

**Comment by luc-github** [comment]
and cpu frequency solved your issue ? this is weird

none of my ESP01 / ESP01S  have a shield and work at 160MHz

**Comment by padcom** [comment]
I know, right?

Anyways - if you'd like we can comment those back in. I don't mind. I'll know what to touch and where when I'll bump into that problem again.

**Comment by luc-github** [comment]
if you do not mind - I would prefer.
That said  you can rename section as esp01s_160MHz  and also add a section like esp01s-80MHz to fit this need, so both sections will be available

**Comment by padcom** [comment]
Done. With a proper commit comment to make sure the information about possible connectivity issues is not lost.

**Comment by luc-github** [comment]
Merged - thank you ^_^

**Comment by padcom** [comment]
It might be interesting for people to see what's needed to get the ESP3D working with SKR 1.4 and 1.4 Turbo boards. I've put together some instruction so that I won't forget it next time :)

http://padcom13.blogspot.com/2020/09/esp3d-on-skr-1414-turbo-with-esp01s.html

**Comment by padcom** [comment]
Oh and btw I tried another module Today with 160MHz and it works like a charm. Maybe the other module is just broken...

**Comment by luc-github** [comment]
@all-contributors please add @padcom for code improvement

**Pull request merged**
