### PR TITLE
Reducing the memory imprint of ESP8266 firmware

### PR DESCRIPTION
**Pull request by treepleks**
Luc,

You'll find all my changes in (almost uniquely) atomic commits below. I did some refactoring in webinterface.cpp and also massively used PROGMEM/F() strings.
There is also some 'french' typo editing.

I would look to each commit if I were you.

This reduces the flash size from 307 372 bytes to 304 292 and (theoretical) RAM usage from  43 342 bytes to 40 462. So 3 kB of Flash and 3kB of RAM saved.

### CODE REVIEW

**Comment by luc-github** [comment]
Thanks I will review the code this week

**Comment by luc-github** [comment]
But I have compilation error if MDNS and SSDP are disabled in same time

**Comment by luc-github** [comment]
OK I have imported the PR locally without changes about Admin user neither  the change (https://github.com/treepleks/ESP8266/commit/f48c2ea5135be57ada53137dcbcf98d76b32647f#commitcomment-15529152)neither the unsupported F() macro in SSDP functions
And now doing some testing before merging

**Comment by luc-github** [comment]
I is running for more than 10h and no crash - so far so good

**Comment by luc-github** [comment]
code implemented 
Thanks a lot

**Comment by MirkoUgoliniDev** [comment]
Hi Luc,

Any chance to implement push notification on errors or printing end process?

Best regards

Mirko

**Comment by luc-github** [comment]
@MirkoUgoliniDev please open new issue - this one is closed and not related
also please elaborate your query - how do you imagine this would work ?
>push notification   

 you mean in UI or external message ?
>notification on errors or printing end process   

based on which trigger ?

I am open to anything but need more details

**Comment by luc-github** [comment]
@all-contributors please add @treepleks  for code improvement

**Pull request closed without merging**
